on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - lts/*
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: echo "y" | rm -Rf dist

      - run: git clone -b v4-dev --depth=1 --single-branch https://github.com/ColorlibHQ/AdminLTE.git

      - run: |
          cd AdminLTE
          npm i
          npx gulp production
          mv dist ../dist

      - run: echo "y" | rm -R AdminLTE

      - uses: peter-evans/create-pull-request@v3
