on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - lts/*
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
